#!/bin/bash

export ORIENTDB_HOME=/var/vcap/packages/orientdb
export JAVA_HOME=/var/vcap/packages/java

case $1 in

    start)
        $ORIENTDB_HOME/bin/orientdb.sh start
        ;;

    stop)
        $ORIENTDB_HOME/bin/orientdb.sh stop
        ;;

    status)
        $ORIENTDB_HOME/bin/orientdb.sh status
        ;;

    *)
        echo "Usage: orientdb_ctl {start|stop|status}"
        ;;
esac
